### ISSUE TITLE
Menu not working anymore

### ISSUE THREAD

**Issue by Sapphiratelaemara** [DrNseven/Warframe#7]
Menu items are no longer clickable in newest build. They highlight but nothing changes.

**Comment by DrNseven** [comment]
I disabled it, the invisible cursor can cause accidental selections while menu is shown. You can reenable it in main.h

if (GetAsyncKeyState(VK_LBUTTON) & 1)
{
	//return 1; //mouse selection OFF
	return 1; //mouse selection ON
}
